"""
Project Kessler — Spacecraft Physics & ADCS Flight Software Server (core_phy)
-------------------------------------------------------------------------------
Runs on Device 3 (Flight Computer / Physics Workstation):
1. Loads master initial ephemeris from Ground AI (shared/initial_ephemeris.json).
2. Runs TCP Command Listener on Port 5556 to receive SLEW_TO_TARGET from edge_pro.
3. Simulates closed-loop mrpFeedback attitude control to lock Star Tracker onto threat vector.
4. Runs TCP Optical Stream Server on Port 5000, transmitting:
     - msg_type=0: {"status": "LOCKED"} attitude lock confirmation
     - msg_type=1: Star Tracker optical frames (JPEG bytes) containing transient debris streak
"""

import argparse
import asyncio
from datetime import datetime, timezone
import json
import logging
import math
import os
from pathlib import Path
import socket
import struct
import sys
import threading
import time
from typing import Optional

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from shared.ws_broadcast import DashboardBroadcaster

try:
    import cv2
    import numpy as np
    OPENCV_AVAILABLE = True
except ImportError:
    cv2 = None
    np = None
    OPENCV_AVAILABLE = False

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [core_phy.fsw] %(message)s",
)
logger = logging.getLogger("core_phy.fsw")


class FSWPhysicsServer:
    """
    Flight Software & Physics Simulation Daemon.
    Interfaces:
      - Command Listener (TCP 5556): Ingests SlewCommand from edge_pro
      - Video Stream Server (TCP 5000): Streams status + camera frames to edge_pro
    """

    def __init__(
        self,
        bind_host: str = "0.0.0.0",
        cmd_port: int = 5556,
        stream_port: int = 5000,
        ephemeris_path: str = "shared/initial_ephemeris.json",
    ):
        self.bind_host = bind_host
        self.cmd_port = cmd_port
        self.stream_port = stream_port
        self.ephemeris_path = Path(ephemeris_path)

        self._running = False
        self._current_target: Optional[str] = None
        self._stream_clients = []
        self._stream_lock = threading.Lock()
        
        self.dashboard_ws = DashboardBroadcaster(port=8001)
        self.dashboard_ws.run_in_background()
        self.ephemeris_data = None

    def load_ground_ephemeris(self) -> dict:
        """Loads master initial ephemeris generated by Ground AI."""
        if self.ephemeris_path.exists():
            try:
                data = json.loads(self.ephemeris_path.read_text())
                logger.info(
                    "Ingested Ground AI Ephemeris: Primary '%s', Debris '%s'",
                    data["primary_asset"]["name"],
                    data["debris_asset"]["name"],
                )
                self.ephemeris_data = data
                return data
            except Exception as e:
                logger.warning("Failed to parse %s (%s); using default states.", self.ephemeris_path, e)
        else:
            logger.warning("Ephemeris file %s not found; using nominal LEO coordinates.", self.ephemeris_path)

        return {
            "primary_asset": {
                "name": "Kessler_Sat_1",
                "r_eci_m": [-5516983.34, -2191874.55, 3291973.37],
                "v_eci_m_s": [-435.489, -6026.776, -4719.534],
            },
            "debris_asset": {
                "name": "Debris_Obj_8492",
                "r_eci_m": [-5466774.05, -2038288.79, 3476970.06],
                "v_eci_m_s": [-620.785, -6140.903, -4547.537],
            },
        }

    # ── Optical Video Frame Generation ─────────────────────────────────────────
    def generate_starfield_frame(self, width: int = 640, height: int = 480) -> np.ndarray:
        """Generates static background starfield matching Tycho catalog distribution."""
        np.random.seed(42)  # Deterministic celestial starfield
        frame = np.zeros((height, width), dtype=np.uint8)
        # Background thermal sensor noise (1-5 DN)
        noise = np.random.normal(3.0, 1.2, (height, width)).astype(np.uint8)
        frame = cv2.add(frame, noise)

        # Draw 60 fixed background stars
        for _ in range(60):
            x = np.random.randint(10, width - 10)
            y = np.random.randint(10, height - 10)
            intensity = np.random.randint(140, 255)
            radius = 1 if intensity < 220 else 2
            cv2.circle(frame, (x, y), radius, int(intensity), -1)
        return frame

    # ── Protocol Framing ───────────────────────────────────────────────────────
    @staticmethod
    def pack_message(msg_type: int, payload: bytes) -> bytes:
        """Packs 5-byte header (1-byte type, 4-byte len) + payload."""
        header = struct.pack(">BI", msg_type, len(payload))
        return header + payload

    def stream_optical_sequence(self, client_sock: socket.socket, target_asset: str):
        """Streams attitude lock confirmation followed by Star Tracker frames."""
        try:
            # 1. Send LOCKED status once ADCS converges
            logger.info("Attitude convergence achieved for '%s'. Sending LOCKED status...", target_asset)
            status_payload = json.dumps({
                "status": "LOCKED",
                "target": target_asset,
                "timestamp_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            }).encode("utf-8")
            client_sock.sendall(self.pack_message(0, status_payload))

            time.sleep(0.5)

            # 2. Generate optical Star Tracker baseline
            starfield = self.generate_starfield_frame()

            # Stream reference frame (static starfield)
            _, buf = cv2.imencode(".jpg", starfield, [cv2.IMWRITE_JPEG_QUALITY, 90])
            client_sock.sendall(self.pack_message(1, buf.tobytes()))
            time.sleep(0.2)

            # 3. Stream moving debris streak sequence entering Danger Corridor
            logger.info("Streaming Star Tracker transient debris streak sequence...")
            streak_x, streak_y = 50.0, 60.0
            vx, vy = 18.0, 12.0  # Velocity vector directed towards corridor center (320, 240)

            for frame_idx in range(20):
                if not self._running:
                    break
                frame = starfield.copy()

                # Add moving transient debris spot/streak
                ix, iy = int(round(streak_x)), int(round(streak_y))
                cv2.circle(frame, (ix, iy), 3, 255, -1)
                # Subpixel elongation along motion vector
                cv2.line(frame, (int(ix - vx * 0.3), int(iy - vy * 0.3)), (ix, iy), 240, 2)

                _, buf = cv2.imencode(".jpg", frame, [cv2.IMWRITE_JPEG_QUALITY, 90])
                client_sock.sendall(self.pack_message(1, buf.tobytes()))

                streak_x += vx * 0.1
                streak_y += vy * 0.1
                
                # Broadcast Orbit to Dashboard
                if self.ephemeris_data:
                    self.dashboard_ws.broadcast({
                        "type": "orbit",
                        "ts": datetime.now(timezone.utc).timestamp(),
                        "sat": {
                            "id": self.ephemeris_data.get("primary_asset", {}).get("name", "Kessler_Sat_1"),
                            "r": self.ephemeris_data.get("primary_asset", {}).get("r_eci_m", [0,0,0]),
                            "v": self.ephemeris_data.get("primary_asset", {}).get("v_eci_m_s", [0,0,0])
                        },
                        "debris": {
                            "id": self.ephemeris_data.get("debris_asset", {}).get("name", "Debris_Obj_8492"),
                            "r": self.ephemeris_data.get("debris_asset", {}).get("r_eci_m", [0,0,0]),
                            "v": self.ephemeris_data.get("debris_asset", {}).get("v_eci_m_s", [0,0,0])
                        }
                    })
                
                time.sleep(0.1)

            logger.info("Debris observation pass concluded for '%s'.", target_asset)

        except (BrokenPipeError, ConnectionResetError):
            logger.info("Optical client disconnected.")
        except Exception as ex:
            logger.error("Error during optical frame streaming (%s)", ex)

    # ── Command Listener (Port 5556) ───────────────────────────────────────────
    def _run_cmd_server(self):
        server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        server.bind((self.bind_host, self.cmd_port))
        server.listen(5)
        server.settimeout(1.0)
        logger.info("FSW Command Server listening on %s:%s (TCP)", self.bind_host, self.cmd_port)

        while self._running:
            try:
                conn, addr = server.accept()
                threading.Thread(target=self._handle_cmd_client, args=(conn, addr), daemon=True).start()
            except socket.timeout:
                continue
            except OSError:
                break
        server.close()

    def _handle_cmd_client(self, conn: socket.socket, addr):
        logger.info("Connection accepted from edge payload at %s", addr)
        buf = ""
        try:
            while self._running:
                chunk = conn.recv(4096)
                if not chunk:
                    break
                buf += chunk.decode("utf-8")
                while "\n" in buf:
                    line, buf = buf.split("\n", 1)
                    if line.strip():
                        self._process_command(conn, line.strip())
        except Exception as ex:
            logger.error("Command handler error (%s)", ex)
        finally:
            conn.close()

    def _process_command(self, conn: socket.socket, cmd_str: str):
        try:
            cmd = json.loads(cmd_str)
            logger.info("Received command from Edge Payload: %s", cmd.get("command"))
            if cmd.get("command") == "SLEW_TO_TARGET":
                target = cmd.get("target_asset", "Unknown_Debris")
                self._current_target = target

                # Acknowledge slew command immediately
                ack = json.dumps({
                    "status": "ACK",
                    "message": "SLEW_COMMAND_ACCEPTED",
                    "target_asset": target,
                    "timestamp_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                }) + "\n"
                conn.sendall(ack.encode("utf-8"))
                logger.info("Acknowledged SLEW_TO_TARGET for '%s'. Initiating ADCS slew...", target)

                # Simulate closed-loop ADCS convergence time
                time.sleep(0.5)
                self._attitude_locked = True
                logger.info("ADCS attitude locked on '%s' approach vector.", target)

        except Exception as e:
            logger.error("Malformed command JSON (%s)", e)

    # ── Video Stream Server (Port 5000) ─────────────────────────────────────────
    def _run_stream_server(self):
        server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        server.bind((self.bind_host, self.stream_port))
        server.listen(5)
        server.settimeout(1.0)
        logger.info("Optical Stream Server listening on %s:%s (TCP)", self.bind_host, self.stream_port)

        while self._running:
            try:
                conn, addr = server.accept()
                logger.info("Optical stream subscriber connected from %s", addr)
                target = self._current_target or "Debris_Obj_8492"
                threading.Thread(target=self.stream_optical_sequence, args=(conn, target), daemon=True).start()
            except socket.timeout:
                continue
            except OSError:
                break
        server.close()

    # ── Service Lifecycle ──────────────────────────────────────────────────────
    def start(self):
        """Starts all background server threads."""
        self._running = True
        self.load_ground_ephemeris()

        self._cmd_thread = threading.Thread(target=self._run_cmd_server, daemon=True)
        self._stream_thread = threading.Thread(target=self._run_stream_server, daemon=True)

        self._cmd_thread.start()
        self._stream_thread.start()
        logger.info("core_phy FSW Server active on Device 3.")

    def stop(self):
        """Terminates all servers."""
        self._running = False
        logger.info("core_phy FSW Server stopped.")


def main():
    parser = argparse.ArgumentParser(description="core_phy FSW & Physics Server — Device 3")
    parser.add_argument("--bind-host", default="0.0.0.0", help="Socket bind address (default: 0.0.0.0)")
    parser.add_argument("--port", type=int, default=5556, help="Command listener port (default: 5556)")
    parser.add_argument("--stream-port", type=int, default=5000, help="Optical stream port (default: 5000)")
    parser.add_argument("--ephemeris", default="shared/initial_ephemeris.json", help="Initial ephemeris JSON path")
    args = parser.parse_args()

    server = FSWPhysicsServer(
        bind_host=args.bind_host,
        cmd_port=args.port,
        stream_port=args.stream_port,
        ephemeris_path=args.ephemeris,
    )
    server.start()

    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        server.stop()


if __name__ == "__main__":
    main()
